# Generated by Django 4.2.3 on 2023-09-19 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0013_search_on_fio_and_update_unique_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritearticle',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='created_at',
            ),
            preserve_default=False,
        ),
    ]
