[tool.black]
skip-string-normalization=true
skip-magic-trailing-comma=false
line-length=89

[tool.flake8]
# ignore=['E501']
exclude=['.git', 'env/', 'venv/', 'temp/', '*.md', '__pycache__/']
max-cognitive-complexity=10
max-line-length=89

[tool.isort]
known_first_party=['users', 'api', 'core', 'likes']
profile='black'

[tool.mypy]
exclude=['venv/']
ignore_missing_imports=true
